apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-rest
spec:
  selector:
    matchLabels:
      app: post-rest
  replicas: 1
  template:
    metadata:
      labels:
        app: post-rest
    spec:
      containers:
        - name: post-rest
          image: spring-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081